name: Eclipse Dirigible
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: true
  coderay:
    coderay_line_numbers: true
    coderay_css: class
highlighter: rouge
baseurl:
url: http://dirigible.io
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - CNAME
  - README.md

defaults:
  -
    scope:
      path: _posts/blogs
      type: posts
    values:
      layout: post
      category: blogs
      tag: blogs
  -
    scope:
      path: _posts/news
      type: posts
    values:
      layout: post
  -
    scope:
      path: _posts/apps
      type: posts
    values:
      layout: app
      category: apps
