name: Dirigible
baseurl:
url: http://dirigible.io
gems:
  - jekyll-sitemap

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]

#markdown: kramdown

kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: true
    coderay_css: class

highlighter: pygments # default python pygments have been replaced by pygments.rb
  