site_name: Eclipse Dirigible News
site_url: https://www.dirigible.io/news/

nav:
    - 'News': 'index.md'
    - '2018':
      - 'jPrime 2018': '2018/05/31/news-jprime-2018.md'
    - '2017':
      - 'UnitedDev Conference 2017': '2017/04/07/news-uniteddev-2017.md'
      - 'EclipseConverge US 2017': '2017/03/20/news-eclipseconverge-2017.md'
      - 'SAP d-kom Sofia 2017': '2017/03/09/news-d-kom-sap-2017.md'
    - '2016':
      - 'InnoWeek SAP Labs 2016': '2016/12/02/news-innoweek-sap-2016.md'
      - 'Java2Days 2016': '2016/11/16/news-java2days-2016.md'
      - 'EclipseCon Europe 2016': '2016/10/30/news-eclipsecon-eu-2016.md'
      - 'Dirigible Labs is live!': '2016/06/17/news-dirigiblelabs.md'
      - 'Brainstormers at HackFMI7': '2016/05/30/news-hackfmi7.md'
      - 'Fast Prototyping in Front of Your Customer - Presentation': '2016/04/18/fast-prototyping-in-front-of-your-customer.md'
      - 'Cloud Development with Dirigible in the Eyes of a Java-saurus - Presentation': '2016/03/08/eclipsecon.md'
      - 'What is New in Dirigible @ d-kom Sofia 2016 - Presentation': '2016/03/01/d-kom.md'
      - 'Docker image for Dirigible': '2016/01/26/news-docker.md'
    - '2015':
      - 'Session by Vladimir Pavlov about Dirigible has been accepted for EclipseCon NA 2016!': '2015/12/16/news-vlado-session-eclipsecon-na-2016.md'
      - 'Dirigible Workshop CodeWeek - Feedback': '2015/10/17/news-dirigible-workshop-codeweek-feedback.md'
      - 'Dirigible Workshop CodeWeek': '2015/10/09/news-dirigible-workshop-codeweek.md'
      - 'Dirigible - integrated environment for developing applications in the Cloud': '2015/10/06/news-dirigible-in-cio-bg.md'
      - 'Eclipse Cloud Development - focusing on development in the Cloud': '2015/09/24/news-ecd-in-cio-bg.md'
      - 'BoF at EclipseCon Europe 2015 scheduled': '2015/09/23/news-bof-eclipsecon-eu-2015.md'
      - 'New Trial Instance at Eclipse.org': '2015/08/24/news-dirigible-new-trial-instance.md'
      - 'Dirigible officially became Eclipse Project': '2015/05/08/news-dirigible-eclipse-project.md'
      - 'Introduction to Eclipse Cloud Developer Tooling': '2015/03/09/news-introduction-to-the-team.md'

theme:
  favicon: /img/favicon.png
  logo: /img/logo/dirigible-logo.png
  name: mkdocs
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

repo_url: https://github.com/eclipse/dirigible
repo_name: eclipse/dirigible
edit_uri: ../../dirigible-io/dirigible-io.github.io/edit/master/docs-news/docs

copyright: Copyright Â© 2010-2021 Eclipse Foundation, Inc. All Rights Reserved. Eclipse is a registered trademark of the Eclipse Foundation, Inc. Dirigible is a trademark of the Eclipse Foundation, Inc.
extra:
  homepage: https://www.dirigible.io
  analytics:
    provider: google
    property: UA-49027147-1
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirigible_io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/slack
      link: https://slack.dirigible.io
