site_name: Eclipse Dirigible Help Portal
site_url: https://www.dirigible.io/help/

theme:
  favicon: ../img/favicon.png
  logo: ../img/logo/dirigible-logo.png
  name: mkdocs
  features:
    - navigation.instant
extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji
    - meta
    - admonition
    - pymdownx.details

repo_url: https://github.com/eclipse/dirigible
repo_name: eclipse/dirigible
edit_uri: ../../dirigible-io/dirigible-io.github.io/edit/master/docs-help/docs

copyright: Copyright Â© 2010-2021 Eclipse Foundation, Inc. All Rights Reserved. Eclipse is a registered trademark of the Eclipse Foundation, Inc. Dirigible is a trademark of the Eclipse Foundation, Inc.
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirigible_io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/slack
      link: https://eclipse-dirigible.slack.com/

google_analytics:
  - UA-49027147-1
  - auto