site_name: Eclipse Dirigible Documentation
site_url: https://www.dirigible.io/help/

nav:
    - Welcome: 'index.md'
    - Getting Started:
      - 'development/index.md'
      - Tutorials:
        - Development:
          - Bookstore:
            - 'tutorials/application-development/bookstore/index.md'
            - Database: 'tutorials/application-development/bookstore/database.md'
            - API: 'tutorials/application-development/bookstore/api.md'
            - User Interface: 'tutorials/application-development/bookstore/ui.md'
          - Scheduled Job:
            - 'tutorials/application-development/scheduled-job/index.md'
            - Database: 'tutorials/application-development/scheduled-job/database.md'
            - Job Handler: 'tutorials/application-development/scheduled-job/handler.md'
            - Scheduled Job: 'tutorials/application-development/scheduled-job/job.md'
          - File Upload: 'tutorials/application-development/file-upload.md'
          - Shell Command: 'tutorials/application-development/shell-command.md'
          - Listener of a Queue: 'tutorials/application-development/listener-queue.md'
          - Kafka Producer and Consumer: 'tutorials/application-development/kafka.md'
        - Modeling:
          - Generate Application from Model: 'tutorials/modeling/generate-application-from-model.md'
          - BPMN Process: 'tutorials/modeling/bpmn-process.md'
        - Customizations:
          - IDE:
            - View: 'tutorials/customizations/ide/create-view.md'
            - Perspective: 'tutorials/customizations/ide/create-perspective.md'
          - Custom Stack:
            - 'tutorials/customizations/custom-stack/index.md'
            - Branding: 'tutorials/customizations/custom-stack/branding.md'
            - Facade: 'tutorials/customizations/custom-stack/facade.md'
            - Dependency: 'tutorials/customizations/custom-stack/dependency.md'
      - Setup: 
        - Tomcat: 'setup/index.md'
        - Docker: 'setup/docker.md'
        - Kubernetes:
          - 'setup/kubernetes/index.md'
          - Google Kubernetes Engine: 'setup/kubernetes/google-kubernetes-engine.md'
          - Azure Kubernetes Service: 'setup/kubernetes/azure-kubernetes-service.md'
          - Red Hat OpenShift: 'setup/kubernetes/red-hat-openshift.md'
          - SAP BTP Kyma: 'setup/kubernetes/sap-btp-kyma.md'
          - Addons:
            - Keycloak: 'setup/kubernetes/addons/keycloak.md'
            - PostgreSQL: 'setup/kubernetes/addons/postgresql.md'
            - GCP DNS Zone: 'setup/kubernetes/addons/google-dns-zone.md'
            - GKE cluster: 'setup/kubernetes/addons/gke-cluster.md'
            - Azure DNS Zone: 'setup/kubernetes/addons/azure-dns-zone.md'
            - Letsencrypt: 'setup/kubernetes/addons/letsencrypt.md'
            - Istio: 'setup/kubernetes/addons/istio.md'
          - Helm: 'setup/kubernetes/helm.md'
        - Cloud Foundry: 'setup/cloud-foundry.md'
        - Environment Variables: 'setup/setup-environment-variables.md'
      - Overview: 
        - 'overview/index.md'
        - Features: 'overview/features.md'
        - Architecture: 'overview/architecture.md'
        - Artifacts:
          - 'development/artifacts/index.md'
          - Data Files: 'development/artifacts/data-files.md'
          - Database Table: 'development/artifacts/database-table.md'
        - Editors & Modelers: 'overview/editors-modelers.md'
        - Engines: 'overview/engines.md'
        - Runtime Services: 'overview/runtime-services.md'
        - Concepts:
          - 'development/concepts/index.md'
          - Dynamic Applications: 'development/concepts/dynamic-applications.md'
          - Entity Service: 'development/concepts/entity-service.md'
          - Extension Definitions: 'development/concepts/extensions.md'
          - Generation: 'development/concepts/generation.md'
          - Mobile Applications: 'development/concepts/mobile-apps.md'
          - Publishing: 'development/concepts/publishing.md'
          - Registry: 'development/concepts/registry.md'
          - Repository: 'development/concepts/repository.md'
          - REST: 'development/concepts/rest.md'
          - Web Content: 'development/concepts/web-content.md'
          - Workspace: 'development/concepts/workspace.md'
      - Extensions:
        - Extensions Overview: 'development/extensions/index.md'
        - Editor: 'development/extensions/editor.md'
        - Perspective: 'development/extensions/perspective.md'
        - Template: 'development/extensions/template.md'
        - View: 'development/extensions/view.md'
      - IDE:
        - IDE Overview: 'development/ide/index.md'
        - About: 'development/ide/about.md'
        - Access Editor: 'development/ide/editor-access.md'
        - CSV Editor: 'development/ide/editor-csv.md'
        - CSVIM Editor: 'development/ide/editor-csvim.md'
        - Monaco Editor: 'development/ide/editor-monaco.md'
        - Modelers:
          - BPMN: 'development/ide/modelers/bpmn.md'
          - Database Schema: 'development/ide/modelers/database-schema.md'
          - Entity Data: 'development/ide/modelers/entity-data.md'
          - Form Designer: 'development/ide/modelers/form-designer.md'
        - Perspectives:
          - Database: 'development/ide/perspectives/database.md'
          - Debugger: 'development/ide/perspectives/debugger.md'
          - Documents: 'development/ide/perspectives/documents.md'
          - Git: 'development/ide/perspectives/git.md'
          - Operations: 'development/ide/perspectives/operations.md'
          - Repository: 'development/ide/perspectives/repository.md'
          - Terminal: 'development/ide/perspectives/terminal.md'
          - Workbench: 'development/ide/perspectives/workbench.md'
        - Views:
          - About: 'development/ide/views/about.md'
          - Access: 'development/ide/views/access.md'
          - Configurations: 'development/ide/views/configurations.md'
          - Console: 'development/ide/views/console.md'
          - Constraints: 'development/ide/views/constraints.md'
          - Database: 'development/ide/views/database.md'
          - Data Structures: 'development/ide/views/datastructures.md'
          - Debugger: 'development/ide/views/debugger.md'
          - Discussions: 'development/ide/views/discussions.md'
          - Documents: 'development/ide/views/documents.md'
          - Extensions: 'development/ide/views/extensions.md'
          - Git: 'development/ide/views/git.md'
          - History: 'development/ide/views/history.md'
          - Import: development/ide/views/import.md
          - Jobs: 'development/ide/views/jobs.md'
          - Listeners: 'development/ide/views/listeners.md'
          - Logs: 'development/ide/views/logs.md'
          - Plugins: 'development/ide/views/plugins.md'
          - Previews: 'development/ide/views/preview.md'
          - Registry: 'development/ide/views/registry.md'
          - Repository: 'development/ide/views/repository.md'
          - Result: 'development/ide/views/resultview.md'
          - Roles: 'development/ide/views/roles.md'
          - Search: 'development/ide/views/search.md'
          - Snapshot: 'development/ide/views/snapshot.md'
          - SQL: 'development/ide/views/sql.md'
          - Staging: 'development/ide/views/staging.md'
          - Terminal: 'development/ide/views/terminal.md'
          - Web Sockets: 'development/ide/views/websockets.md'
          - Workspace: 'development/ide/views/workspace.md'
      - Developer Resources:
        - Development & Operations: 'development/devops.md'
        - Keyboard Shortcuts: 'developer-resources/keyboard-shortcuts.md'
        - Java Remote Debugging: 'developer-resources/java-remote-debugging.md'
        - Cheat Sheet: 'developer-resources/cheat-sheet.md'
      - FAQ: 'overview/faq.md'
    - Community:
      - 'community.md'
      - Credits: 'overview/credits.md'
      - License: 'overview/license.md'

theme:
  favicon: /img/favicon.png
  logo: img/logo/dirigible-logo.png
  name: mkdocs
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    
extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

repo_url: https://github.com/eclipse/dirigible
repo_name: eclipse/dirigible
edit_uri: ../../dirigible-io/dirigible-io.github.io/edit/master/docs-help/docs

copyright: Copyright Â© 2010-2021 Eclipse Foundation, Inc. All Rights Reserved. Eclipse is a registered trademark of the Eclipse Foundation, Inc. Dirigible is a trademark of the Eclipse Foundation, Inc.
extra:
  homepage: https://www.dirigible.io
  analytics:
    provider: google
    property: UA-49027147-1
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirigible_io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/slack
      link: https://slack.dirigible.io

plugins:
  - social:
      cards_color:
        fill: "#FECC04"
        text: "#2D2D2D"
  - search