site_name: Eclipse Dirigible Help Portal
site_url: https://www.dirigible.io/help/

nav:
    - Welcome: 'index.md'
    - Overview: 
      - The Eclipse Dirigible Project: 'overview/index.md'
      - Editors & Modelers: 'overview/editors-modelers.md'
      - Architecture: 'overview/architecture.md'
      - Engines: 'overview/engines.md'
      - Features: 'overview/features.md'
      - Runtime Services: 'overview/runtime-services.md'
      - FAQ: 'overview/faq.md'
      - License: 'overview/license.md'
      - Credits: 'overview/credits.md'
    - Setup: 
      - Tomcat: 'setup/index.md'
      - Docker: 'setup/docker.md'
      - Kubernetes: 'setup/kubernetes.md'
      - Kyma: 'setup/kyma.md'
      - Helm: 'setup/helm.md'
      - Cloud Foundry: 'setup/cloud-foundry.md'
      - Environment Variables: 'setup/setup-environment-variables.md'
    - Development: 
      - Getting Started: 'development/index.md'
      - Development & Operations: 'development/devops.md'
      - Artifacts:
        - Artifacts Overview: 'development/artifacts/index.md'
        - Data Files: 'development/artifacts/data-files.md'
        - Database Table: 'development/artifacts/database-table.md'
      - Concepts:
        - Concepts Overview: 'development/concepts/index.md'
        - Dynamic Applications: 'development/concepts/dynamic-applications.md'
        - Entity Service: 'development/concepts/entity-service.md'
        - Extension Definitions: 'development/concepts/extensions.md'
        - Generation: 'development/concepts/generation.md'
        - Mobile Applications: 'development/concepts/mobile-apps.md'
        - Publishing: 'development/concepts/publishing.md'
        - Registry: 'development/concepts/registry.md'
        - Repository: 'development/concepts/repository.md'
        - REST: 'development/concepts/rest.md'
        - Web Content: 'development/concepts/web-content.md'
        - Workspace: 'development/concepts/workspace.md'
      - Extensions:
        - Extensions Overview: 'development/extensions/index.md'
        - Editor: 'development/extensions/editor.md'
        - Perspective: 'development/extensions/perspective.md'
        - Template: 'development/extensions/template.md'
        - View: 'development/extensions/view.md'
      - IDE:
        - IDE Overview: 'development/ide/index.md'
        - About: 'development/ide/about.md'
        - CSV Editor: 'development/ide/editor-csv.md'
        - Monaco Editor: 'development/ide/editor-monaco.md'
        - Modelers:
          - BPMN: 'development/ide/modelers/bpmn.md'
          - Database Schema: 'development/ide/modelers/database-schema.md'
          - Entity Data: 'development/ide/modelers/entity-data.md'
          - Form Designer: 'development/ide/modelers/form-designer.md'
        - Perspectives:
          - Database: 'development/ide/perspectives/database.md'
          - Debugger: 'development/ide/perspectives/debugger.md'
          - Documents: 'development/ide/perspectives/documents.md'
          - Git: 'development/ide/perspectives/git.md'
          - Operations: 'development/ide/perspectives/operations.md'
          - Repository: 'development/ide/perspectives/repository.md'
          - Terminal: 'development/ide/perspectives/terminal.md'
          - Workbench: 'development/ide/perspectives/workbench.md'
        - Views:
          - About: 'development/ide/views/about.md'
          - Access: 'development/ide/views/access.md'
          - Configurations: 'development/ide/views/configurations.md'
          - Console: 'development/ide/views/console.md'
          - Database: 'development/ide/views/database.md'
          - Data Structures: 'development/ide/views/datastructures.md'
          - Debugger: 'development/ide/views/debugger.md'
          - Documents: 'development/ide/views/documents.md'
          - Extensions: 'development/ide/views/extensions.md'
          - Git: 'development/ide/views/git.md'
          - History: 'development/ide/views/history.md'
          - Import: development/ide/views/import.md
          - Jobs: 'development/ide/views/jobs.md'
          - Listeners: 'development/ide/views/listeners.md'
          - Logs: 'development/ide/views/logs.md'
          - Plugins: 'development/ide/views/plugins.md'
          - Previews: 'development/ide/views/preview.md'
          - Registry: 'development/ide/views/registry.md'
          - Repository: 'development/ide/views/repository.md'
          - Roles: 'development/ide/views/roles.md'
          - Search: 'development/ide/views/search.md'
          - Snapshot: 'development/ide/views/snapshot.md'
          - SQL: 'development/ide/views/sql.md'
          - Staging: 'development/ide/views/staging.md'
          - Terminal: 'development/ide/views/terminal.md'
          - Web Sockets: 'development/ide/views/websockets.md'
          - Workspace: 'development/ide/views/workspace.md'
    - Tips & Tricks:
      - Cheat Sheet: 'tips-&-tricks/cheat-sheet.md'
    - Community: 'community.md'
        

theme:
  favicon: /img/favicon.png
  logo: /img/logo/dirigible-logo.png
  name: mkdocs
  custom_dir: overrides
  features:
    - navigation.instant
    
extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

repo_url: https://github.com/eclipse/dirigible
repo_name: eclipse/dirigible
edit_uri: ../../dirigible-io/dirigible-io.github.io/edit/master/docs-help/docs

copyright: Copyright Â© 2010-2021 Eclipse Foundation, Inc. All Rights Reserved. Eclipse is a registered trademark of the Eclipse Foundation, Inc. Dirigible is a trademark of the Eclipse Foundation, Inc.
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirigible_io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/slack
      link: https://eclipse-dirigible.slack.com/

google_analytics:
  - UA-49027147-1
  - auto
