name: Eclipse Dirigible
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: true
  coderay:
    coderay_line_numbers: false
    coderay_css: class
highlighter: rouge
baseurl:
url: http://dirigible.io
plugins:
  - jekyll-feed

exclude:
  - CNAME
  - README.md

defaults:
  -
    scope:
      path: _posts/blogs
      type: posts
    values:
      layout: blog
      category: blogs
      tag: blogs
  -
    scope:
      path: _posts/news
      type: posts
    values:
      layout: news
  -
    scope:
      path: _posts/releases
      type: posts
    values:
      layout: release

theme: jekyll-theme-merlot
